### ISSUE TITLE
JavaScript Capstone Project

### ISSUE THREAD

**Issue by Thermiee** [levy002/Javascript-Capstone#21]
https://github.com/levy002/Javascript-Capstone

There are two people on the team.

**Comment by Ghiftee** [comment]
## STATUS: APPROVED ♻️♻️
Hi TEAM, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀  
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
- You can consider all opened issues for team 3 as they are not necessary in this project.

![](https://camo.githubusercontent.com/bedaa87cf63a4eb642948910de3563599306694dfb7118796862f47e55d90651/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f546466794b724e3748475449592f67697068792e676966)

Cheers and Happy coding!👏👏👏

**Comment by levy002** [comment]
> ## STATUS: APPROVED ♻️♻️
> Hi TEAM,
> 
> Your project is complete! There is nothing else to say other than... it's time to merge it 🚀 Congratulations! 🎉
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> * You can consider all opened issues for team 3 as they are not necessary in this project.
> 
> ![](https://camo.githubusercontent.com/bedaa87cf63a4eb642948910de3563599306694dfb7118796862f47e55d90651/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f546466794b724e3748475449592f67697068792e676966)
> 
> Cheers and Happy coding!👏👏👏

Thank you @Ghiftee 😃
